server {
    listen 80; #Nginx écoute sur le port 80
    index index.php index.html; #Fichier par défaut à servir
    root /var/www/html/public; #Point d'entrée Laravel — toujours public/, jamais la racine

    location / {
        try_files $uri $uri/ /index.php?$query_string; #Cherche le fichier, sinon passe à Laravel — c'est ce qui permet le routing Laravel
    }

    location ~ \.php$ {
        fastcgi_pass backend:9000; #Redirige les requêtes PHP vers le conteneur "backend" sur le port 9000 (PHP-FPM), backend = nom du service dans docker-compose.yml
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name; #Dit à PHP quel fichier exécuter
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all; #Empêche l'accès aux fichiers cachés (comme .env) pour des raisons de sécurité, sauf les fichiers dans .well-known
    }
}